### ISSUE TITLE
Investigate tests throwing error `no such table: test_keyspace_x_0.tbl`

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-cdc-go#22]
Investigate why following tests:
- TestConsumerCallsEmptyCallback
- TestConsumerResumesWithTableBackedProgressReporter
- TestConsumerHonorsTableTTL
- TestTypes

Throw an error:
```
2024/08/19 21:51:16.620781 stream_batch.go:105: error while sending a query (will retry): no such table: test_keyspace_1724104276532690272_0.tbl
```
And whether this error should fail the test.

**Comment by sylwiaszunejko** [comment]
It is throwing the error because here: https://github.com/scylladb/scylla-cdc-go/blob/master/change.go#L561 it uses `KeyspaceMetadata` before it is updated after creating the table. When I changed `eventDebounceTime` in gocql https://github.com/scylladb/gocql/blob/master/events.go#L55 to something smaller it stopped throwing an error. We could add 1 second sleep in scylla-cdc-go before reading metadata or just ignore this error as it looks to be non issue @dkropachev
